name: go_translator
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.1
  flutter_tts: ^4.2.3
  google_mlkit_translation: ^0.13.0
  
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.6.2
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.0
  # device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1
  riverpod_generator: ^4.0.3
  analyzer: ^9.0.0   # ðŸ‘ˆ ADD THIS
  # custom_lint: ^0.8.0
  # flutter_lints: ^6.0.0
  # import_sorter: ^4.6.0
 

dependency_overrides:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

import_sorter:
  comments: false
