name: go_translator
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
isar_version: &isar_version 3.3.0-dev.3
dependencies:
 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.1
  flutter_tts: ^4.2.3
  google_mlkit_translation: ^0.13.0
  
  intl: ^0.20.2
  isar_community: 
    version: *isar_version
  isar_community_flutter_libs: # contains Isar Core
    version: *isar_version
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  logger: ^2.6.2
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.3
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1
  isar_community_generator: 
    version: *isar_version
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
 

dependency_overrides:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

import_sorter:
  comments: false
